"use client";

import SymbolSearch from "@/components/layout/SymbolSearch";
import { TIMEFRAMES } from "@/lib/config";

/**
 * The seven Signal History filters, all composable and all URL-synced by the
 * page above so a filtered view can be shared or bookmarked.
 *
 * "Strategy" is one control over two query parameters: the top group selects
 * the *generator* (`source`), the bottom group selects an *analyst that
 * supported the signal* (`analyst`). They are different questions — "signals
 * the scanner produced" versus "signals the Range analyst backed" — and a
 * single dropdown keeps both one click away without pretending they are the
 * same field.
 */

export interface SignalFilters {
  symbol: string;
  /** one of the three analyst keys — signals this analyst actively supported */
  analyst: string;
  /** COMPOSITE | CONFLUENCE — which engine produced the signal */
  source: string;
  side: string;
  outcome: string;
  timeframe: string;
  from: string;
  to: string;
  /** confidence band key, resolved to min/max by `bandRange` */
  band: string;
}

export const EMPTY_FILTERS: SignalFilters = {
  symbol: "",
  analyst: "",
  source: "",
  side: "",
  outcome: "",
  timeframe: "",
  from: "",
  to: "",
  band: "",
};

const BANDS: Record<string, { label: string; min?: number; max?: number }> = {
  "": { label: "Any confidence" },
  low: { label: "Low — under 70%", max: 69.99 },
  moderate: { label: "Moderate — 70-79%", min: 70, max: 79.99 },
  high: { label: "High — 80-89%", min: 80, max: 89.99 },
  veryHigh: { label: "Very high — 90%+", min: 90 },
};

export function bandRange(band: string): { min?: number; max?: number } {
  const b = BANDS[band];
  return b ? { min: b.min, max: b.max } : {};
}

/** Query string for `/api/signals`, omitting every unset filter. */
export function filtersToQuery(f: SignalFilters, limit = 60): string {
  const { min, max } = bandRange(f.band);
  const q = new URLSearchParams();
  if (f.symbol) q.set("symbol", f.symbol);
  if (f.analyst) q.set("analyst", f.analyst);
  if (f.source) q.set("source", f.source);
  if (f.side) q.set("side", f.side);
  if (f.outcome) q.set("outcome", f.outcome);
  if (f.timeframe) q.set("timeframe", f.timeframe);
  if (f.from) q.set("from", f.from);
  if (f.to) q.set("to", f.to);
  if (min !== undefined) q.set("minConfidence", String(min));
  if (max !== undefined) q.set("maxConfidence", String(max));
  q.set("limit", String(limit));
  return q.toString();
}

export function activeFilterCount(f: SignalFilters): number {
  return Object.values(f).filter(Boolean).length;
}

const SELECT_CLASS =
  "rounded-lg border border-white/10 bg-base-800 px-2 py-1.5 text-xs text-slate-200 outline-none focus:border-neon-cyan/50";

export default function FilterBar({
  filters,
  onChange,
  onReset,
  resultCount,
  overFetched,
}: {
  filters: SignalFilters;
  onChange: (patch: Partial<SignalFilters>) => void;
  onReset: () => void;
  resultCount: number;
  overFetched?: boolean;
}) {
  const active = activeFilterCount(filters);

  return (
    <div className="glass space-y-2 p-3">
      <div className="flex flex-wrap items-center gap-2">
        <Field label="Coin">
          <div className="flex items-center gap-1">
            <SymbolSearch
              symbol={filters.symbol}
              onSelect={(s) => onChange({ symbol: s })}
              placeholder="All coins"
            />
            {filters.symbol && (
              <button
                onClick={() => onChange({ symbol: "" })}
                className="rounded px-1 text-[11px] text-slate-500 hover:text-bear"
                aria-label="Clear coin filter"
              >
                ✕
              </button>
            )}
          </div>
        </Field>

        <Field label="Strategy / analyst">
          <select
            className={SELECT_CLASS}
            value={filters.analyst ? `analyst:${filters.analyst}` : filters.source ? `source:${filters.source}` : ""}
            onChange={(e) => {
              const v = e.target.value;
              if (!v) return onChange({ analyst: "", source: "" });
              const [kind, value] = v.split(":");
              onChange(kind === "analyst" ? { analyst: value, source: "" } : { source: value, analyst: "" });
            }}
          >
            <option value="">All strategies</option>
            <optgroup label="Generated by">
              <option value="source:CONFLUENCE">Confluence scanner</option>
              <option value="source:COMPOSITE">Composite engine</option>
            </optgroup>
            <optgroup label="Supported by analyst">
              <option value="analyst:chart">Chart Analyst</option>
              <option value="analyst:candleClose">Candle Close Expansion</option>
              <option value="analyst:range">Range Trading</option>
            </optgroup>
          </select>
        </Field>

        <Field label="Direction">
          <select
            className={SELECT_CLASS}
            value={filters.side}
            onChange={(e) => onChange({ side: e.target.value })}
          >
            <option value="">LONG &amp; SHORT</option>
            <option value="BUY">LONG only</option>
            <option value="SELL">SHORT only</option>
          </select>
        </Field>

        <Field label="Outcome">
          <select
            className={SELECT_CLASS}
            value={filters.outcome}
            onChange={(e) => onChange({ outcome: e.target.value })}
          >
            <option value="">Any outcome</option>
            <option value="active">Active</option>
            <option value="successful">Successful</option>
            <option value="failed">Failed</option>
            <option value="expired">Expired</option>
          </select>
        </Field>

        <Field label="Timeframe">
          <select
            className={SELECT_CLASS}
            value={filters.timeframe}
            onChange={(e) => onChange({ timeframe: e.target.value })}
          >
            <option value="">All timeframes</option>
            {TIMEFRAMES.map((tf) => (
              <option key={tf} value={tf}>
                {tf}
              </option>
            ))}
          </select>
        </Field>

        <Field label="Confidence">
          <select
            className={SELECT_CLASS}
            value={filters.band}
            onChange={(e) => onChange({ band: e.target.value })}
          >
            {Object.entries(BANDS).map(([key, b]) => (
              <option key={key} value={key}>
                {b.label}
              </option>
            ))}
          </select>
        </Field>

        <Field label="From">
          <input
            type="date"
            value={filters.from}
            onChange={(e) => onChange({ from: e.target.value })}
            className={SELECT_CLASS}
          />
        </Field>

        <Field label="To">
          <input
            type="date"
            value={filters.to}
            onChange={(e) => onChange({ to: e.target.value })}
            className={SELECT_CLASS}
          />
        </Field>

        <div className="ml-auto flex items-center gap-2 self-end">
          <span className="font-mono text-[10px] text-slate-500">
            {resultCount} shown
            {active > 0 && ` · ${active} filter${active === 1 ? "" : "s"}`}
          </span>
          {active > 0 && (
            <button
              onClick={onReset}
              className="rounded-lg bg-white/5 px-2 py-1 text-[11px] text-slate-400 transition-colors hover:bg-white/10 hover:text-slate-200"
            >
              Clear all
            </button>
          )}
        </div>
      </div>

      {overFetched && (
        <p className="text-[10px] leading-relaxed text-neon-amber/80">
          More rows match than fit this page. The analyst and successful/failed filters are applied
          after the query, so narrow the date range to see the rest.
        </p>
      )}
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-0.5">
      <span className="text-[9px] uppercase tracking-wider text-slate-500">{label}</span>
      {children}
    </label>
  );
}
